#!/bin/bash

export ROOT_DIR=$PWD
export CONFIG_FILE_PATH=$PWD/etc
export OUTPUT_PATH=$PWD/results
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# check install state
if [[ ! -f "installed.ok" ]];then
    echo -e "${RED}Error${NC}: Please execute the ${GREEN}install.sh${NC} before run this shell script"
    exit
fi

mkdir -p $OUTPUT_PATH

ListExamples() {
    echo "All avaiable experiments: "
    for file in `ls experiments/`
    do
        echo "      ${file}"
    done
}

ExecuteExample(){
    run="experiments/${1}/run-${1}.sh"
    if [[ -f "experiments/${1}/run-${1}.sh" ]];then
        export RUN_ARGS=$2
        export EXAMPLE_NAME=$1
        bash $run
    else
        echo -e "${RED}Error${NC}: $1 has been not implemented, Please \`./run list\` get avaiable experiment list"
        exit
    fi
}

ClearResults(){
    case $1 in
        "all")
            echo "Clear all results"
            rm $OUTPUT_PATH -rf || exit "$?"
            ;;
        *)
            if [[ -d "$OUTPUT_PATH/$1" ]]; then
                rm "$OUTPUT_PATH/$1" -rf || exit "$?"
            else
                echo -e "${RED}Error${NC}: $OUTPUT_PATH/$1 is not exist"
                exit
            fi
            ;;
        esac
        
}

NewExample(){
    # create empty directory
    mkdir $ROOT_DIR/examples/$1 || exit "Fail to create example : $1"
    # create experiments directory and script templete
    mkdir $ROOT_DIR/experiments/$1 || exit "Fail to create example : $1"
    echo "echo \"running $1\"" > $ROOT_DIR/experiments/$1/run-$1.sh
    # create a empty configuration file
    touch $ROOT_DIR/etc/$1.conf
}

DelExample(){
    rm $ROOT_DIR/examples/$1 -rf
    rm $ROOT_DIR/experiments/$1 -rf
    rm $ROOT_DIR/etc/$1.conf -rf
    echo "Delete success"
}

case $1 in
    "list")
        ListExamples
        ;;
    "clear")
        ClearResults $2
        ;;
    "new")
        NewExample $2
        ;;
    "delete")
        DelExample $2
        ;;
    *)
        ExecuteExample $1 $2
        ;;
esac



